env:
  browser: true
  mocha: true
  node: true
  es6: true
plugins:
  - mocha
  - react
  - compat
parser: babel-eslint
parserOptions:
  sourceType: module
extends:
  - 'airbnb'
globals:
  expect: true
  assert: true
rules:
  comma-dangle: off
  arrow-body-style: off
  no-console: off
  no-alert: off
  import/extensions: off
  import/no-unresolved: off
  import/imports-first: off
  import/newline-after-import: off
  import/no-extraneous-dependencies: off
  space-before-function-paren: off
  compat/compat: 2
  react/prefer-stateless-function: 1
